-- ============================================================================
-- Payroll schema repair — Payroll / PayrollRun
-- ============================================================================
--
-- GENERATED by scripts/gen-payroll-schema-sql.ts from lib/payroll-schema.ts.
-- Don't edit by hand: change the spec there and re-run the generator, so the
-- manual script and the runtime self-heal stay identical.
--
-- WHY THIS EXISTS: the payroll models were added to schema.prisma but never got
-- a migration (`grep PayrollRun prisma/migrations` returns nothing), and Vercel
-- can't run `migrate deploy` because DIRECT_URL isn't configured. Prod's tables
-- were built by hand from an older revision, so three different things drifted,
-- each surfacing as its own 500:
--
--   1. missing columns   -> The column PayrollRun.processedBy does not exist
--   2. case-folded twins -> Null constraint violation on the fields:
--                           (processedby). A column added with unquoted DDL:
--                           Postgres folds it to lower case, where Prisma —
--                           which always quotes — can never see it.
--   3. wrong types       -> operator does not exist: text <> "PayrollStatus".
--                           status is TEXT in prod, an enum in the schema.
--
-- Each is reconciled below against the declared spec, in that order.
--
-- HOW TO RUN: paste the whole file into the Supabase SQL editor and run it once.
-- Safe to re-run: matching columns are left untouched and the constraint blocks
-- swallow their own duplicates, so the single transaction the editor wraps this
-- in is never aborted.
--
-- WHAT IT WON'T DO: no column is ever dropped and no row is deleted. New columns
-- land on existing rows with their defaults. A type conversion keeps the values
-- it can parse; the ones it can't (an empty string in a number column, a status
-- outside the enum) fall back to that column's default rather than failing the
-- whole repair.
--
-- The app self-heals on its own the first time a payroll route is hit, so this
-- file is only for fixing the database up front.
-- ============================================================================


DO $do$ BEGIN
    CREATE TYPE "PayrollStatus" AS ENUM ('DRAFT', 'PROCESSED', 'PAID');
EXCEPTION WHEN duplicate_object THEN NULL;
END $do$;


CREATE TABLE IF NOT EXISTS "PayrollRun" (
    "id" TEXT NOT NULL,
    CONSTRAINT "PayrollRun_pkey" PRIMARY KEY ("id")
);


DO $do$
DECLARE
    expected TEXT[] := ARRAY['lockedAt', 'processedBy', 'totalGross', 'totalNet', 'totalPfEmployer', 'totalEsiEmployer', 'totalLwf', 'totalTds', 'createdAt', 'updatedAt'];
    col    TEXT;
    legacy TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'PayrollRun'
    ) THEN RETURN; END IF;
    FOREACH col IN ARRAY expected LOOP
        -- Per-column handler: the Supabase editor runs this file as
        -- ONE transaction, so an unhandled error on any single
        -- column rolls back every other fix in the file. Skip the
        -- column, keep the repair.
        BEGIN
            legacy := lower(col);
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'PayrollRun' AND column_name = legacy
            ) THEN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'PayrollRun' AND column_name = col
                ) THEN
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP NOT NULL', 'PayrollRun', legacy);
                ELSE
                    EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', 'PayrollRun', legacy, col);
                END IF;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'skipped legacy-case fix on %.%: %', 'PayrollRun', col, SQLERRM;
        END;
    END LOOP;
END $do$;


ALTER TABLE "PayrollRun"
    ADD COLUMN IF NOT EXISTS "month" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "year" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "status" "PayrollStatus" NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS "lockedAt" TIMESTAMP(3),
    ADD COLUMN IF NOT EXISTS "processedBy" TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "totalGross" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalNet" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalPfEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalEsiEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalLwf" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalTds" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;


DO $do$
DECLARE
    spec   RECORD;
    actual TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'PayrollRun'
    ) THEN RETURN; END IF;

    FOR spec IN SELECT * FROM (VALUES
    ('month', 'int4', 'INTEGER', 'ROUND(NULLIF("month"::text, '''')::numeric)::integer', true, '0'),
    ('year', 'int4', 'INTEGER', 'ROUND(NULLIF("year"::text, '''')::numeric)::integer', true, '0'),
    ('status', 'PayrollStatus', '"PayrollStatus"', '"status"::text::"PayrollStatus"', true, '''DRAFT'''),
    ('lockedAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("lockedAt"::text, '''')::timestamp(3)', false, ''),
    ('processedBy', 'text', 'TEXT', '"processedBy"::text', true, ''''''),
    ('totalGross', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalGross"::text, '''')::double precision', true, '0'),
    ('totalNet', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalNet"::text, '''')::double precision', true, '0'),
    ('totalPfEmployer', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalPfEmployer"::text, '''')::double precision', true, '0'),
    ('totalEsiEmployer', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalEsiEmployer"::text, '''')::double precision', true, '0'),
    ('totalLwf', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalLwf"::text, '''')::double precision', true, '0'),
    ('totalTds', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalTds"::text, '''')::double precision', true, '0'),
    ('createdAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("createdAt"::text, '''')::timestamp(3)', true, 'CURRENT_TIMESTAMP'),
    ('updatedAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("updatedAt"::text, '''')::timestamp(3)', true, 'CURRENT_TIMESTAMP')
    ) AS t(col, want_udt, type_sql, using_sql, not_null, def_sql)
    LOOP
        -- Per-column handler: the Supabase editor runs this file as
        -- ONE transaction, so an unhandled error on any single
        -- column rolls back every other fix in the file. A column
        -- whose type can't be reconciled is skipped with a NOTICE
        -- instead of taking the whole repair down. Written as an IF
        -- rather than CONTINUE because a jump out of a block that
        -- has an EXCEPTION clause is best avoided.
        BEGIN
            SELECT c.udt_name INTO actual
            FROM information_schema.columns c
            WHERE c.table_schema = 'public' AND c.table_name = 'PayrollRun'
              AND c.column_name = spec.col;

            -- Absent (addColumns handles that) or already right: leave it.
            IF actual IS NOT NULL AND actual <> spec.want_udt THEN
                -- The old default is expressed in the old type, so it
                -- has to go before the column can change type.
                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP DEFAULT', 'PayrollRun', spec.col);

                -- A value outside the enum would abort the cast. Park
                -- those on the default rather than failing the repair.
                IF spec.want_udt = 'PayrollStatus' THEN
                    EXECUTE format(
                        'UPDATE %I SET %I = %L WHERE %I IS NULL OR %I::text <> ALL (%L::text[])',
                        'PayrollRun', spec.col, 'DRAFT', spec.col, spec.col,
                        '{DRAFT,PROCESSED,PAID}');
                END IF;

                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE %s USING %s',
                               'PayrollRun', spec.col, spec.type_sql, spec.using_sql);

                IF spec.def_sql <> '' THEN
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET DEFAULT %s',
                                   'PayrollRun', spec.col, spec.def_sql);
                END IF;

                IF spec.not_null THEN
                    -- The cast can leave NULLs behind (empty strings
                    -- become NULL), so fill them before re-asserting.
                    IF spec.def_sql <> '' THEN
                        EXECUTE format('UPDATE %I SET %I = %s WHERE %I IS NULL',
                                       'PayrollRun', spec.col, spec.def_sql, spec.col);
                    END IF;
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', 'PayrollRun', spec.col);
                END IF;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'skipped type fix on %.%: %', 'PayrollRun', spec.col, SQLERRM;
        END;
    END LOOP;
END $do$;


DO $do$
DECLARE
    rel   REGCLASS := to_regclass('public."PayrollRun"');
    dupes BIGINT;
BEGIN
    IF rel IS NULL THEN RETURN; END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'PayrollRun' AND column_name = 'id'
    ) THEN RETURN; END IF;

    -- Already keyed (primary or unique) on exactly "id"?
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = rel AND contype IN ('p', 'u')
          AND conkey = ARRAY[(
              SELECT attnum FROM pg_attribute
              WHERE attrelid = rel AND attname = 'id'
                AND attnum > 0 AND NOT attisdropped
          )]::smallint[]
    ) THEN RETURN; END IF;

    -- The constraint NAME is a relation name too, so a leftover
    -- index called "<table>_pkey" — one hand-created without a
    -- matching pg_constraint row, which the check above cannot
    -- see — makes ADD CONSTRAINT fail with 42P07 and, in the
    -- Supabase editor, rolls back the entire repair file.
    IF to_regclass('public."PayrollRun_pkey"') IS NOT NULL THEN RETURN; END IF;

    EXECUTE format('UPDATE %I SET "id" = gen_random_uuid()::text WHERE "id" IS NULL OR "id" = ''''', 'PayrollRun');

    EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM %I GROUP BY "id" HAVING count(*) > 1) d', 'PayrollRun')
        INTO dupes;
    IF dupes > 0 THEN
        RAISE NOTICE '%: % duplicate id(s), leaving the table unkeyed', 'PayrollRun', dupes;
        RETURN;
    END IF;

    EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY ("id")', 'PayrollRun', 'PayrollRun_pkey');
EXCEPTION WHEN OTHERS THEN
    -- Same rule as the foreign keys below: the primary key is the
    -- least important thing in this file, and nothing may be
    -- sacrificed to add it. Never let it abort the transaction.
    RAISE NOTICE 'skipped primary key on %: %', 'PayrollRun', SQLERRM;
END $do$;


CREATE TABLE IF NOT EXISTS "Payroll" (
    "id" TEXT NOT NULL,
    CONSTRAINT "Payroll_pkey" PRIMARY KEY ("id")
);


DO $do$
DECLARE
    expected TEXT[] := ARRAY['employeeId', 'payrollRunId', 'basicFull', 'daFull', 'hraFull', 'washingFull', 'conveyanceFull', 'lwwFull', 'bonusFull', 'otherFull', 'grossFullMonth', 'basicSalary', 'lwwEarned', 'otDays', 'overtimePay', 'productionIncentive', 'grossSalary', 'pfEmployee', 'pfEmployer', 'esiEmployee', 'esiEmployer', 'canteenDays', 'otherDeductions', 'totalDeductions', 'netSalary', 'workingDays', 'presentDays', 'leaveDays', 'lwpDays', 'overtimeHrs', 'overtimeRate', 'siteId', 'processedAt', 'processedBy', 'paidAt', 'paidBy', 'createdAt', 'updatedAt'];
    col    TEXT;
    legacy TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'Payroll'
    ) THEN RETURN; END IF;
    FOREACH col IN ARRAY expected LOOP
        -- Per-column handler: the Supabase editor runs this file as
        -- ONE transaction, so an unhandled error on any single
        -- column rolls back every other fix in the file. Skip the
        -- column, keep the repair.
        BEGIN
            legacy := lower(col);
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'Payroll' AND column_name = legacy
            ) THEN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'Payroll' AND column_name = col
                ) THEN
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP NOT NULL', 'Payroll', legacy);
                ELSE
                    EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', 'Payroll', legacy, col);
                END IF;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'skipped legacy-case fix on %.%: %', 'Payroll', col, SQLERRM;
        END;
    END LOOP;
END $do$;


ALTER TABLE "Payroll"
    ADD COLUMN IF NOT EXISTS "employeeId" TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "payrollRunId" TEXT,
    ADD COLUMN IF NOT EXISTS "month" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "year" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "basicFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "daFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "hraFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "washingFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "conveyanceFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "lwwFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "bonusFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "otherFull" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "grossFullMonth" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "basicSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "da" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "hra" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "washing" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "conveyance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "lwwEarned" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "bonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "allowances" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "otDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "overtimePay" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "productionIncentive" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "grossSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "pfEmployee" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "pfEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "esiEmployee" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "esiEmployer" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "pt" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "lwf" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "tds" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "canteenDays" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "canteen" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "penalty" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "advance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "otherDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "totalDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "netSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "ctc" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "workingDays" INTEGER NOT NULL DEFAULT 26,
    ADD COLUMN IF NOT EXISTS "presentDays" INTEGER NOT NULL DEFAULT 26,
    ADD COLUMN IF NOT EXISTS "leaveDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "lwpDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "overtimeHrs" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "overtimeRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "siteId" TEXT,
    ADD COLUMN IF NOT EXISTS "status" "PayrollStatus" NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS "processedAt" TIMESTAMP(3),
    ADD COLUMN IF NOT EXISTS "processedBy" TEXT,
    ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3),
    ADD COLUMN IF NOT EXISTS "paidBy" TEXT,
    ADD COLUMN IF NOT EXISTS "remarks" TEXT,
    ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;


DO $do$
DECLARE
    spec   RECORD;
    actual TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'Payroll'
    ) THEN RETURN; END IF;

    FOR spec IN SELECT * FROM (VALUES
    ('employeeId', 'text', 'TEXT', '"employeeId"::text', true, ''''''),
    ('payrollRunId', 'text', 'TEXT', '"payrollRunId"::text', false, ''),
    ('month', 'int4', 'INTEGER', 'ROUND(NULLIF("month"::text, '''')::numeric)::integer', true, '0'),
    ('year', 'int4', 'INTEGER', 'ROUND(NULLIF("year"::text, '''')::numeric)::integer', true, '0'),
    ('basicFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("basicFull"::text, '''')::double precision', true, '0'),
    ('daFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("daFull"::text, '''')::double precision', true, '0'),
    ('hraFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("hraFull"::text, '''')::double precision', true, '0'),
    ('washingFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("washingFull"::text, '''')::double precision', true, '0'),
    ('conveyanceFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("conveyanceFull"::text, '''')::double precision', true, '0'),
    ('lwwFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("lwwFull"::text, '''')::double precision', true, '0'),
    ('bonusFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("bonusFull"::text, '''')::double precision', true, '0'),
    ('otherFull', 'float8', 'DOUBLE PRECISION', 'NULLIF("otherFull"::text, '''')::double precision', true, '0'),
    ('grossFullMonth', 'float8', 'DOUBLE PRECISION', 'NULLIF("grossFullMonth"::text, '''')::double precision', true, '0'),
    ('basicSalary', 'float8', 'DOUBLE PRECISION', 'NULLIF("basicSalary"::text, '''')::double precision', true, '0'),
    ('da', 'float8', 'DOUBLE PRECISION', 'NULLIF("da"::text, '''')::double precision', true, '0'),
    ('hra', 'float8', 'DOUBLE PRECISION', 'NULLIF("hra"::text, '''')::double precision', true, '0'),
    ('washing', 'float8', 'DOUBLE PRECISION', 'NULLIF("washing"::text, '''')::double precision', true, '0'),
    ('conveyance', 'float8', 'DOUBLE PRECISION', 'NULLIF("conveyance"::text, '''')::double precision', true, '0'),
    ('lwwEarned', 'float8', 'DOUBLE PRECISION', 'NULLIF("lwwEarned"::text, '''')::double precision', true, '0'),
    ('bonus', 'float8', 'DOUBLE PRECISION', 'NULLIF("bonus"::text, '''')::double precision', true, '0'),
    ('allowances', 'float8', 'DOUBLE PRECISION', 'NULLIF("allowances"::text, '''')::double precision', true, '0'),
    ('otDays', 'float8', 'DOUBLE PRECISION', 'NULLIF("otDays"::text, '''')::double precision', true, '0'),
    ('overtimePay', 'float8', 'DOUBLE PRECISION', 'NULLIF("overtimePay"::text, '''')::double precision', true, '0'),
    ('productionIncentive', 'float8', 'DOUBLE PRECISION', 'NULLIF("productionIncentive"::text, '''')::double precision', true, '0'),
    ('grossSalary', 'float8', 'DOUBLE PRECISION', 'NULLIF("grossSalary"::text, '''')::double precision', true, '0'),
    ('pfEmployee', 'float8', 'DOUBLE PRECISION', 'NULLIF("pfEmployee"::text, '''')::double precision', true, '0'),
    ('pfEmployer', 'float8', 'DOUBLE PRECISION', 'NULLIF("pfEmployer"::text, '''')::double precision', true, '0'),
    ('esiEmployee', 'float8', 'DOUBLE PRECISION', 'NULLIF("esiEmployee"::text, '''')::double precision', true, '0'),
    ('esiEmployer', 'float8', 'DOUBLE PRECISION', 'NULLIF("esiEmployer"::text, '''')::double precision', true, '0'),
    ('pt', 'float8', 'DOUBLE PRECISION', 'NULLIF("pt"::text, '''')::double precision', true, '0'),
    ('lwf', 'float8', 'DOUBLE PRECISION', 'NULLIF("lwf"::text, '''')::double precision', true, '0'),
    ('tds', 'float8', 'DOUBLE PRECISION', 'NULLIF("tds"::text, '''')::double precision', true, '0'),
    ('canteenDays', 'int4', 'INTEGER', 'ROUND(NULLIF("canteenDays"::text, '''')::numeric)::integer', true, '0'),
    ('canteen', 'float8', 'DOUBLE PRECISION', 'NULLIF("canteen"::text, '''')::double precision', true, '0'),
    ('penalty', 'float8', 'DOUBLE PRECISION', 'NULLIF("penalty"::text, '''')::double precision', true, '0'),
    ('advance', 'float8', 'DOUBLE PRECISION', 'NULLIF("advance"::text, '''')::double precision', true, '0'),
    ('otherDeductions', 'float8', 'DOUBLE PRECISION', 'NULLIF("otherDeductions"::text, '''')::double precision', true, '0'),
    ('totalDeductions', 'float8', 'DOUBLE PRECISION', 'NULLIF("totalDeductions"::text, '''')::double precision', true, '0'),
    ('netSalary', 'float8', 'DOUBLE PRECISION', 'NULLIF("netSalary"::text, '''')::double precision', true, '0'),
    ('ctc', 'float8', 'DOUBLE PRECISION', 'NULLIF("ctc"::text, '''')::double precision', true, '0'),
    ('workingDays', 'int4', 'INTEGER', 'ROUND(NULLIF("workingDays"::text, '''')::numeric)::integer', true, '26'),
    ('presentDays', 'int4', 'INTEGER', 'ROUND(NULLIF("presentDays"::text, '''')::numeric)::integer', true, '26'),
    ('leaveDays', 'float8', 'DOUBLE PRECISION', 'NULLIF("leaveDays"::text, '''')::double precision', true, '0'),
    ('lwpDays', 'float8', 'DOUBLE PRECISION', 'NULLIF("lwpDays"::text, '''')::double precision', true, '0'),
    ('overtimeHrs', 'float8', 'DOUBLE PRECISION', 'NULLIF("overtimeHrs"::text, '''')::double precision', true, '0'),
    ('overtimeRate', 'float8', 'DOUBLE PRECISION', 'NULLIF("overtimeRate"::text, '''')::double precision', true, '0'),
    ('siteId', 'text', 'TEXT', '"siteId"::text', false, ''),
    ('status', 'PayrollStatus', '"PayrollStatus"', '"status"::text::"PayrollStatus"', true, '''DRAFT'''),
    ('processedAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("processedAt"::text, '''')::timestamp(3)', false, ''),
    ('processedBy', 'text', 'TEXT', '"processedBy"::text', false, ''),
    ('paidAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("paidAt"::text, '''')::timestamp(3)', false, ''),
    ('paidBy', 'text', 'TEXT', '"paidBy"::text', false, ''),
    ('remarks', 'text', 'TEXT', '"remarks"::text', false, ''),
    ('createdAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("createdAt"::text, '''')::timestamp(3)', true, 'CURRENT_TIMESTAMP'),
    ('updatedAt', 'timestamp', 'TIMESTAMP(3)', 'NULLIF("updatedAt"::text, '''')::timestamp(3)', true, 'CURRENT_TIMESTAMP')
    ) AS t(col, want_udt, type_sql, using_sql, not_null, def_sql)
    LOOP
        -- Per-column handler: the Supabase editor runs this file as
        -- ONE transaction, so an unhandled error on any single
        -- column rolls back every other fix in the file. A column
        -- whose type can't be reconciled is skipped with a NOTICE
        -- instead of taking the whole repair down. Written as an IF
        -- rather than CONTINUE because a jump out of a block that
        -- has an EXCEPTION clause is best avoided.
        BEGIN
            SELECT c.udt_name INTO actual
            FROM information_schema.columns c
            WHERE c.table_schema = 'public' AND c.table_name = 'Payroll'
              AND c.column_name = spec.col;

            -- Absent (addColumns handles that) or already right: leave it.
            IF actual IS NOT NULL AND actual <> spec.want_udt THEN
                -- The old default is expressed in the old type, so it
                -- has to go before the column can change type.
                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP DEFAULT', 'Payroll', spec.col);

                -- A value outside the enum would abort the cast. Park
                -- those on the default rather than failing the repair.
                IF spec.want_udt = 'PayrollStatus' THEN
                    EXECUTE format(
                        'UPDATE %I SET %I = %L WHERE %I IS NULL OR %I::text <> ALL (%L::text[])',
                        'Payroll', spec.col, 'DRAFT', spec.col, spec.col,
                        '{DRAFT,PROCESSED,PAID}');
                END IF;

                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE %s USING %s',
                               'Payroll', spec.col, spec.type_sql, spec.using_sql);

                IF spec.def_sql <> '' THEN
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET DEFAULT %s',
                                   'Payroll', spec.col, spec.def_sql);
                END IF;

                IF spec.not_null THEN
                    -- The cast can leave NULLs behind (empty strings
                    -- become NULL), so fill them before re-asserting.
                    IF spec.def_sql <> '' THEN
                        EXECUTE format('UPDATE %I SET %I = %s WHERE %I IS NULL',
                                       'Payroll', spec.col, spec.def_sql, spec.col);
                    END IF;
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', 'Payroll', spec.col);
                END IF;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'skipped type fix on %.%: %', 'Payroll', spec.col, SQLERRM;
        END;
    END LOOP;
END $do$;


DO $do$
DECLARE
    rel   REGCLASS := to_regclass('public."Payroll"');
    dupes BIGINT;
BEGIN
    IF rel IS NULL THEN RETURN; END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'Payroll' AND column_name = 'id'
    ) THEN RETURN; END IF;

    -- Already keyed (primary or unique) on exactly "id"?
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = rel AND contype IN ('p', 'u')
          AND conkey = ARRAY[(
              SELECT attnum FROM pg_attribute
              WHERE attrelid = rel AND attname = 'id'
                AND attnum > 0 AND NOT attisdropped
          )]::smallint[]
    ) THEN RETURN; END IF;

    -- The constraint NAME is a relation name too, so a leftover
    -- index called "<table>_pkey" — one hand-created without a
    -- matching pg_constraint row, which the check above cannot
    -- see — makes ADD CONSTRAINT fail with 42P07 and, in the
    -- Supabase editor, rolls back the entire repair file.
    IF to_regclass('public."Payroll_pkey"') IS NOT NULL THEN RETURN; END IF;

    EXECUTE format('UPDATE %I SET "id" = gen_random_uuid()::text WHERE "id" IS NULL OR "id" = ''''', 'Payroll');

    EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM %I GROUP BY "id" HAVING count(*) > 1) d', 'Payroll')
        INTO dupes;
    IF dupes > 0 THEN
        RAISE NOTICE '%: % duplicate id(s), leaving the table unkeyed', 'Payroll', dupes;
        RETURN;
    END IF;

    EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY ("id")', 'Payroll', 'Payroll_pkey');
EXCEPTION WHEN OTHERS THEN
    -- Same rule as the foreign keys below: the primary key is the
    -- least important thing in this file, and nothing may be
    -- sacrificed to add it. Never let it abort the transaction.
    RAISE NOTICE 'skipped primary key on %: %', 'Payroll', SQLERRM;
END $do$;


CREATE UNIQUE INDEX IF NOT EXISTS "PayrollRun_month_year_key" ON "PayrollRun"("month", "year");


CREATE INDEX IF NOT EXISTS "PayrollRun_status_idx" ON "PayrollRun"("status");


CREATE UNIQUE INDEX IF NOT EXISTS "Payroll_employeeId_month_year_key" ON "Payroll"("employeeId", "month", "year");


CREATE INDEX IF NOT EXISTS "Payroll_month_year_idx"   ON "Payroll"("month", "year");


CREATE INDEX IF NOT EXISTS "Payroll_status_idx"       ON "Payroll"("status");


CREATE INDEX IF NOT EXISTS "Payroll_employeeId_idx"   ON "Payroll"("employeeId");


CREATE INDEX IF NOT EXISTS "Payroll_payrollRunId_idx" ON "Payroll"("payrollRunId");


DO $do$ BEGIN
    ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'skipped foreign key: %', SQLERRM;
END $do$;


DO $do$ BEGIN
    ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_payrollRunId_fkey"
    FOREIGN KEY ("payrollRunId") REFERENCES "PayrollRun"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'skipped foreign key: %', SQLERRM;
END $do$;


-- ── Verify ──────────────────────────────────────────────────────────────────
-- Expect PayrollRun = 14 columns, Payroll = 56, and both statuses PayrollStatus.
SELECT table_name, count(*) AS columns
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
GROUP BY table_name
ORDER BY table_name;

SELECT table_name, column_name, udt_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
  AND column_name = 'status'
ORDER BY table_name;

-- Any row here is a leftover lower-cased twin: harmless, but dead weight that
-- Prisma never reads or writes. Expect none.
SELECT table_name, column_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
  AND column_name = lower(column_name)
  AND column_name IN (
      'processedby', 'payrollrunid', 'employeeid', 'lockedat', 'totalgross',
      'totalnet', 'basicsalary', 'netsalary', 'grossfullmonth', 'workingdays',
      'presentdays', 'createdat', 'updatedat'
  )
ORDER BY table_name, column_name;
