// Emits scripts/fix-payroll-schema.sql from the spec in lib/payroll-schema.ts,
// so the manual Supabase script and the runtime self-heal can never drift.
//
//   DATABASE_URL=postgresql://unused npx ts-node --project scripts/tsconfig.gen.json \
//       -r tsconfig-paths/register scripts/gen-payroll-schema-sql.ts
//
// DATABASE_URL only has to parse — nothing connects. It's needed because the
// spec lives beside the runtime heal, which imports the Prisma client.
//
// Re-run it whenever the payroll models change in schema.prisma, and commit the
// result. Nothing at build or request time depends on this file.
import { writeFileSync } from "fs"
import { join } from "path"
import { payrollSchemaSql } from "../lib/payroll-schema"

const HEADER = `-- ============================================================================
-- Payroll schema repair — Payroll / PayrollRun
-- ============================================================================
--
-- GENERATED by scripts/gen-payroll-schema-sql.ts from lib/payroll-schema.ts.
-- Don't edit by hand: change the spec there and re-run the generator, so the
-- manual script and the runtime self-heal stay identical.
--
-- WHY THIS EXISTS: the payroll models were added to schema.prisma but never got
-- a migration (\`grep PayrollRun prisma/migrations\` returns nothing), and Vercel
-- can't run \`migrate deploy\` because DIRECT_URL isn't configured. Prod's tables
-- were built by hand from an older revision, so three different things drifted,
-- each surfacing as its own 500:
--
--   1. missing columns   -> The column PayrollRun.processedBy does not exist
--   2. case-folded twins -> Null constraint violation on the fields:
--                           (processedby). A column added with unquoted DDL:
--                           Postgres folds it to lower case, where Prisma —
--                           which always quotes — can never see it.
--   3. wrong types       -> operator does not exist: text <> "PayrollStatus".
--                           status is TEXT in prod, an enum in the schema.
--
-- Each is reconciled below against the declared spec, in that order.
--
-- HOW TO RUN: paste the whole file into the Supabase SQL editor and run it once.
-- Safe to re-run: matching columns are left untouched and the constraint blocks
-- swallow their own duplicates, so the single transaction the editor wraps this
-- in is never aborted.
--
-- WHAT IT WON'T DO: no column is ever dropped and no row is deleted. New columns
-- land on existing rows with their defaults. A type conversion keeps the values
-- it can parse; the ones it can't (an empty string in a number column, a status
-- outside the enum) fall back to that column's default rather than failing the
-- whole repair.
--
-- The app self-heals on its own the first time a payroll route is hit, so this
-- file is only for fixing the database up front.
-- ============================================================================
`

const { ddl, foreignKeys } = payrollSchemaSql()

// ADD CONSTRAINT has no IF NOT EXISTS, and an unhandled duplicate would roll
// back the editor's transaction, so each FK gets its own exception handler.
const fkBlocks = foreignKeys.map(fk => `DO $do$ BEGIN
    ${fk.trim().replace(/\n\s+/g, "\n    ")};
EXCEPTION WHEN duplicate_object THEN NULL;
END $do$;`)

const VERIFY = `-- ── Verify ──────────────────────────────────────────────────────────────────
-- Expect PayrollRun = 14 columns, Payroll = 56, and both statuses PayrollStatus.
SELECT table_name, count(*) AS columns
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
GROUP BY table_name
ORDER BY table_name;

SELECT table_name, column_name, udt_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
  AND column_name = 'status'
ORDER BY table_name;

-- Any row here is a leftover lower-cased twin: harmless, but dead weight that
-- Prisma never reads or writes. Expect none.
SELECT table_name, column_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name IN ('Payroll', 'PayrollRun')
  AND column_name = lower(column_name)
  AND column_name IN (
      'processedby', 'payrollrunid', 'employeeid', 'lockedat', 'totalgross',
      'totalnet', 'basicsalary', 'netsalary', 'grossfullmonth', 'workingdays',
      'presentdays', 'createdat', 'updatedat'
  )
ORDER BY table_name, column_name;`

const body = [...ddl, ...fkBlocks]
    .map(s => s.trim().replace(/\n {12}/g, "\n").replace(/\n {4}$/, "") + (s.trim().endsWith(";") ? "" : ";"))
    .join("\n\n\n")

writeFileSync(join(__dirname, "fix-payroll-schema.sql"), `${HEADER}\n\n${body}\n\n\n${VERIFY}\n`)
console.log("wrote scripts/fix-payroll-schema.sql")
